services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: yndu_prod
    secrets:
      - postgres_password
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
      - ./src/infrastructure/adapters/postgres/migrations:/migrations:ro
      - ./src/infrastructure/adapters/postgres/bootstrap/prod_init.sql:/docker-entrypoint-initdb.d/001_init.sql:ro
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d yndu_prod']
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - yndu-overlay
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1.00'
          memory: 1G
        reservations:
          memory: 256M

  redis:
    image: redis:7-alpine
    command:
      [
        'sh',
        '-c',
        "redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru --requirepass \"$$(cat /run/secrets/redis_password)\"",
      ]
    secrets:
      - redis_password
    volumes:
      - redis_prod_data:/data
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "redis-cli -a \"$$(cat /run/secrets/redis_password)\" ping | grep PONG",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - yndu-overlay
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          memory: 128M

  backend:
    image: ${REGISTRY:-ghcr.io}/${IMAGE_NAME:-yndu}/backend:${TAG:-latest}
    environment:
      PORT: '8000'
      HOST: '0.0.0.0'
      DATABASE_HOST: postgres
      DATABASE_PORT: '5432'
      DATABASE_USER: postgres
      DATABASE_PASSWORD_FILE: /run/secrets/database_password
      DATABASE_NAME: yndu_prod
      REDIS_HOST: redis
      REDIS_PORT: '6379'
      REDIS_PASSWORD_FILE: /run/secrets/redis_password
      REDIS_DB: '0'
      CORS_ORIGIN: ${CORS_ORIGIN:-https://localhost}
      NODE_ENV: production
      JWT_SECRET_FILE: /run/secrets/jwt_secret
      HASHPAY_API_KEY_FILE: /run/secrets/hashpay_api_key
      HASHPAY_ACCOUNT_ID_FILE: /run/secrets/hashpay_account_id
      BCRYPT_ROUNDS: '12'
      SESSION_TIMEOUT: '600'
      REFRESH_TOKEN_TIMEOUT: '604800'
      MAX_LOGIN_ATTEMPTS: '5'
      LOCKOUT_DURATION: '3600'
      RATE_LIMIT_WINDOW_MS: '900000'
      RATE_LIMIT_MAX: '100'
    secrets:
      - database_password
      - redis_password
      - jwt_secret
      - hashpay_api_key
      - hashpay_account_id
    networks:
      - yndu-overlay
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1.50'
          memory: 1G
        reservations:
          memory: 256M

  frontend:
    image: ${REGISTRY:-ghcr.io}/${IMAGE_NAME:-yndu}/frontend:${TAG:-latest}
    command:
      [
        'sh',
        '-c',
        "export NUXT_SESSION_PASSWORD=\"$$(cat /run/secrets/nuxt_session_password)\" && node .output/server/index.mjs",
      ]
    environment:
      NODE_ENV: production
      DENO_API_URL: http://backend:8000
      NITRO_HOST: 0.0.0.0
      NITRO_PORT: 3000
      NUXT_TELEMETRY_DISABLED: '1'
    secrets:
      - nuxt_session_password
    networks:
      - yndu-overlay
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1.00'
          memory: 1G
        reservations:
          memory: 256M

  users:
    image: ${REGISTRY:-ghcr.io}/${IMAGE_NAME:-yndu}/users:${TAG:-latest}
    environment:
      PORT: '4001'
      BACKEND_URL: 'http://backend:8000'
      NODE_ENV: production
      NODE_OPTIONS: '--max-old-space-size=256'
    networks:
      - yndu-overlay
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          memory: 64M

  inventory:
    image: ${REGISTRY:-ghcr.io}/${IMAGE_NAME:-yndu}/inventory:${TAG:-latest}
    environment:
      PORT: '4002'
      BACKEND_URL: 'http://backend:8000'
      NODE_ENV: production
      NODE_OPTIONS: '--max-old-space-size=256'
    networks:
      - yndu-overlay
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          memory: 64M

  orders:
    image: ${REGISTRY:-ghcr.io}/${IMAGE_NAME:-yndu}/orders:${TAG:-latest}
    environment:
      PORT: '4003'
      BACKEND_URL: 'http://backend:8000'
      NODE_ENV: production
      NODE_OPTIONS: '--max-old-space-size=256'
    networks:
      - yndu-overlay
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          memory: 64M

  gateway:
    image: ${REGISTRY:-ghcr.io}/${IMAGE_NAME:-yndu}/gateway:${TAG:-latest}
    environment:
      PORT: '4000'
      USER_SERVICE_URL: 'http://users:4001/graphql'
      INVENTORY_SERVICE_URL: 'http://inventory:4002/graphql'
      ORDER_SERVICE_URL: 'http://orders:4003/graphql'
      NODE_ENV: production
      NODE_OPTIONS: '--max-old-space-size=256'
    networks:
      - yndu-overlay
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          memory: 64M

  nginx:
    image: nginx:1.27-alpine
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress
      - target: 443
        published: 443
        protocol: tcp
        mode: ingress
    volumes:
      - ./nginx/production.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - yndu-overlay
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          memory: 64M

volumes:
  postgres_prod_data:
  redis_prod_data:

networks:
  yndu-overlay:
    driver: overlay
    attachable: true

secrets:
  postgres_password:
    external: true
    name: yndu_postgres_password
  database_password:
    external: true
    name: yndu_database_password
  redis_password:
    external: true
    name: yndu_redis_password
  jwt_secret:
    external: true
    name: yndu_jwt_secret
  hashpay_api_key:
    external: true
    name: yndu_hashpay_api_key
  hashpay_account_id:
    external: true
    name: yndu_hashpay_account_id
  nuxt_session_password:
    external: true
    name: yndu_nuxt_session_password
