// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/20/2026, 11:53:27 PM
import '@nuxtjs/tailwindcss/config-ctx';
import configMerger from '@nuxtjs/tailwindcss/merger';

import cfg2 from './../../tailwind.config.js';
import cfg3 from './../../tailwind.config.js';
const config = [
  {
    'content': {
      'files': [
        '/app/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}',
        '/app/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}',
        '/app/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}',
        '/app/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}',
        '/app/app/plugins/**/*.{js,ts,mjs}',
        '/app/app/composables/**/*.{js,ts,mjs}',
        '/app/app/utils/**/*.{js,ts,mjs}',
        '/app/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}',
        '/app/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}',
        '/app/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}',
        '/app/app/app.config.{js,ts,mjs}',
      ],
    },
  },
  {},
  cfg2,
  cfg3,
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;
