// Generated by nitro
import type { Serialize, Simplify } from 'nitropack/types';
declare module 'nitropack/types' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T;
  interface InternalApi {
    '/api/auth/login': {
      'post': Simplify<
        Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>
      >;
    };
    '/api/auth/logout': {
      'post': Simplify<
        Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>
      >;
    };
    '/api/auth/register': {
      'post': Simplify<
        Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>
      >;
    };
    '/auth/google': {
      'get': Simplify<
        Serialize<Awaited<ReturnType<typeof import('../../server/routes/auth/google.get').default>>>
      >;
    };
    '/__nuxt_error': {
      'default': Simplify<
        Serialize<
          Awaited<
            ReturnType<
              typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default
            >
          >
        >
      >;
    };
    '/__nuxt_island/**': {
      'default': Simplify<
        Serialize<
          Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>
        >
      >;
    };
    '/api/_auth/session': {
      'delete': Simplify<
        Serialize<
          Awaited<
            ReturnType<
              typeof import('../../node_modules/nuxt-auth-utils/dist/runtime/server/api/session.delete').default
            >
          >
        >
      >;
      'get': Simplify<
        Serialize<
          Awaited<
            ReturnType<
              typeof import('../../node_modules/nuxt-auth-utils/dist/runtime/server/api/session.get').default
            >
          >
        >
      >;
    };
    '/_ipx/**': {
      'default': Simplify<
        Serialize<
          Awaited<
            ReturnType<
              typeof import('../../node_modules/@nuxt/image/dist/runtime/server/routes/_ipx').default
            >
          >
        >
      >;
    };
  }
}
export {};
